## 모두를 위한 머신러닝/딥러닝 강의
김성훈 교수님의 모두를 위한 머신러닝/딥러닝 강의 중 lab 강의의 코드를 구현한 것입니다.
## Lab4 Multivariable linear regression
### Without matrix concept

In [3]:
import tensorflow as tf
### without matrix concept
# Generate sample data
x1_data = [1, 0, 3, 0, 5]
x2_data = [0, 2, 0, 4, 0]
y_data = [1, 2, 3, 4, 5]

# Try to find values for W and b that compute y_data = W * x_data + b
# (We know that W should be 1 and b 0, but Tensorflow will
# figure that out for us.)

W1 = tf.Variable(tf.random_uniform(shape = [1], minval = -1.0, maxval = 1.0))
W2 = tf.Variable(tf.random_uniform(shape = [1], minval = -1.0, maxval = 1.0))
b = tf.Variable(tf.random_uniform(shape = [1], minval = -1.0, maxval = 1.0))


# Our hypothesis
hypothesis = W1 * x1_data + W2 * x2_data + b

# Simplified cost function
cost = tf.reduce_mean(input_tensor = tf.square(hypothesis - y_data))

# Minimize
alpha = tf.Variable(0.1) # Learning rate, alpha
optimizer = tf.train.GradientDescentOptimizer(learning_rate = alpha)
train = optimizer.minimize(cost)

# Before starting, initialize the variables. We will 'run' this first.
init = tf.global_variables_initializer()

# Launch the graph
sess = tf.Session()
sess.run(init)

# Fit the line
for step in range(501):
    sess.run(train)
    if step % 20 == 0:
       print(step, sess.run(cost), sess.run(W1), sess.run(W2), sess.run(b))

0 2.90856 [ 1.64934099] [ 1.10650384] [-0.03451693]
20 0.00215287 [ 1.02891529] [ 1.034307] [-0.10999484]
40 0.000623341 [ 1.0155586] [ 1.01846027] [-0.05918726]
60 0.000180484 [ 1.00837195] [ 1.00993323] [-0.03184813]
80 5.22575e-05 [ 1.0045048] [ 1.00534499] [-0.0171372]
100 1.51306e-05 [ 1.002424] [ 1.00287604] [-0.00922139]
120 4.38124e-06 [ 1.00130439] [ 1.00154769] [-0.00496196]
140 1.26857e-06 [ 1.0007019] [ 1.0008328] [-0.00266994]
160 3.67288e-07 [ 1.00037766] [ 1.00044811] [-0.00143669]
180 1.06304e-07 [ 1.00020313] [ 1.00024104] [-0.00077298]
200 3.08037e-08 [ 1.00010943] [ 1.0001297] [-0.00041589]
220 8.90949e-09 [ 1.00005877] [ 1.00006974] [-0.00022378]
240 2.56952e-09 [ 1.00003159] [ 1.00003755] [-0.00012041]
260 7.48089e-10 [ 1.00001693] [ 1.00002015] [ -6.48035202e-05]
280 2.15994e-10 [ 1.00000906] [ 1.00001085] [ -3.48581416e-05]
300 6.28496e-11 [ 1.00000489] [ 1.00000584] [ -1.87696533e-05]
320 1.90141e-11 [ 1.00000262] [ 1.00000322] [ -1.01460528e-05]
340 5.6275e-12 

### With matrix concept

In [5]:
### with matrix concept
x_data = [[0., 2., 0., 4., 0.], [1., 0., 3., 0., 5.]] # Column 하나가 Data instance 하나
y_data = [1, 2, 3, 4, 5]

# Try to find values for W
W = tf.Variable(tf.random_uniform(shape = [1,2] , minval = -1.0, maxval = 1.0))
b = tf.Variable(tf.random_uniform(shape = [1] , minval = -1.0, maxval = 1.0))

# Our hypothesis
hypothesis = tf.matmul(W, x_data) + b

# Simplified cost function
cost = tf.reduce_mean(input_tensor = tf.square(hypothesis - y_data))

# Minimize
alpha = tf.Variable(0.1) # Learning rate, alpha
optimizer = tf.train.GradientDescentOptimizer(learning_rate = alpha)
train = optimizer.minimize(cost)

# Before starting, initialize the variables. We will 'run' this first.
init = tf.global_variables_initializer()

# Launch the graph
sess = tf.Session()
sess.run(init)

# Fit the line
for step in range(501):
    sess.run(train)
    if step % 20 == 0:
       print(step, sess.run(cost), sess.run(W), sess.run(b))

0 0.108783 [[ 0.72008526  0.81290698]] [ 0.72582608]
20 0.0281598 [[ 0.87592381  0.89542609]] [ 0.39781356]
40 0.00815342 [[ 0.93323576  0.94372976]] [ 0.21405974]
60 0.00236076 [[ 0.96407479  0.9697215 ]] [ 0.11518353]
80 0.000683535 [[ 0.98066896  0.98370749]] [ 0.0619792]
100 0.000197912 [[ 0.98959816  0.99123317]] [ 0.03335042]
120 5.73038e-05 [[ 0.99440289  0.99528259]] [ 0.01794554]
140 1.65913e-05 [[ 0.99698824  0.99746168]] [ 0.00965636]
160 4.8039e-06 [[ 0.99837935  0.9986341 ]] [ 0.005196]
180 1.39102e-06 [[ 0.99912792  0.99926502]] [ 0.00279593]
200 4.02715e-07 [[ 0.99953073  0.99960458]] [ 0.00150446]
220 1.16595e-07 [[ 0.99974751  0.99978721]] [ 0.00080956]
240 3.37657e-08 [[ 0.9998641  0.9998855]] [ 0.00043562]
260 9.76626e-09 [[ 0.99992687  0.99993837]] [ 0.00023442]
280 2.82784e-09 [[ 0.99996066  0.9999668 ]] [ 0.00012615]
300 8.21993e-10 [[ 0.99997884  0.99998212]] [  6.78391661e-05]
320 2.37662e-10 [[ 0.99998862  0.9999904 ]] [  3.65157357e-05]
340 6.96104e-11 [[ 0.99

### With matrix concept and designt matrix concept 

In [7]:
x_data = [[1, 1, 1, 1, 1],
          [0., 2., 0., 4., 0.],
          [1., 0., 3., 0., 5.]] # Column 하나가 Data instance 하나
y_data = [1, 2, 3, 4, 5]

# Try to find values for W
W = tf.Variable(tf.random_uniform(shape = [1,3], minval = -1.0, maxval = 1.0))

# Our hypothesis
hypothesis = tf.matmul(W, x_data)

# Simplified cost function
cost = tf.reduce_mean(input_tensor = tf.square(hypothesis - y_data))

# Minimize
alpha = tf.Variable(0.1) # Learning rate, alpha
optimizer = tf.train.GradientDescentOptimizer(learning_rate = alpha)
train = optimizer.minimize(cost)

# Before starting, initialize the variables. We will 'run' this first.
init = tf.global_variables_initializer()

# Launch the graph
sess = tf.Session()
sess.run(init)

# Fit the line
for step in range(601):
    sess.run(train)
    if step % 20 == 0:
       print(step, sess.run(cost), sess.run(W))

0 4.9709 [[ 1.4306705   0.50922406  1.44215369]]
20 0.0815574 [[ 0.67701286  0.78884298  0.82203329]]
40 0.0236143 [[ 0.3642942   0.88637829  0.90423733]]
60 0.00683731 [[ 0.19602332  0.93886119  0.94847107]]
80 0.00197969 [[ 0.10547833  0.96710175  0.97227263]]
100 0.000573203 [[ 0.05675692  0.98229778  0.98508018]]
120 0.000165967 [[ 0.0305404   0.99047458  0.99197179]]
140 4.8054e-05 [[ 0.01643348  0.99487448  0.99568009]]
160 1.39137e-05 [[ 0.00884275  0.99724203  0.99767554]]
180 4.02851e-06 [[ 0.00475822  0.99851596  0.9987492 ]]
200 1.16654e-06 [[ 0.00256036  0.99920142  0.999327  ]]
220 3.37708e-07 [[ 0.00137774  0.99957031  0.99963796]]
240 9.7807e-08 [[  7.41306401e-04   9.99768794e-01   9.99805093e-01]]
260 2.83047e-08 [[  3.98923003e-04   9.99875605e-01   9.99895155e-01]]
280 8.20309e-09 [[  2.14644475e-04   9.99933064e-01   9.99943674e-01]]
300 2.37015e-09 [[  1.15495735e-04   9.99963999e-01   9.99969661e-01]]
320 6.89127e-10 [[  6.21281069e-05   9.99980628e-01   9.9998372

### Use numpy library with matrix cocnept and design matrix concept
ndarray 형태를 사용할 때는, shape(차원)에 주의하여 사용할 것!

In [15]:
# load the example data
import tensorflow as tf
import numpy as np
xy = np.loadtxt(fname = 'C:/Users/KBS/PycharmProjects/Deep_learning_everyone/Lab4_example.txt', dtype = 'float32', delimiter = ' ',
                unpack = False)
print(xy)

[[ 1.  1.  0.  1.]
 [ 1.  0.  2.  2.]
 [ 1.  3.  0.  3.]
 [ 1.  0.  4.  4.]
 [ 1.  5.  0.  5.]]


In [53]:
# Check shapes of each data
x_data = xy[:,0:-1]
y_data = xy[:,-1].reshape((1,5))
print('x_data = ',x_data,'\ny_data = ', y_data)
print('x_data shape = ',x_data.shape, '\ny_data shape = ',y_data.shape)

x_data =  [[ 1.  1.  0.]
 [ 1.  0.  2.]
 [ 1.  3.  0.]
 [ 1.  0.  4.]
 [ 1.  5.  0.]] 
y_data =  [[ 1.  2.  3.  4.  5.]]
x_data shape =  (5, 3) 
y_data shape =  (1, 5)


In [54]:
# train
W = tf.Variable(tf.random_uniform(shape = [1,x_data.shape[1]], minval = -5.0, maxval = 5.0))

# Our hypothesis
hypothesis = tf.matmul(W, x_data, transpose_b = True)

# Simplified cost function
cost = tf.reduce_mean(tf.square(hypothesis - y_data))

# Minimize
alpha = tf.Variable(0.1) # Learning rate, alpha
optimizer = tf.train.GradientDescentOptimizer(learning_rate = alpha)
train = optimizer.minimize(cost)

# Before starting, initialize the variables. We will 'run' this first.
init = tf.global_variables_initializer()

# Launch the graph
sess = tf.Session()
sess.run(init)

# Fit the line
for step in range(601):
    sess.run(train)
    if step % 20 == 0:
       print(step, sess.run(cost), sess.run(W))

0 14.5991 [[-4.17051125  0.79576302  2.08599019]]
20 0.751798 [[-2.05549097  1.54032922  1.6410979 ]]
40 0.217677 [[-1.10604036  1.29074681  1.34496891]]
60 0.0630265 [[-0.59514999  1.15644813  1.18562448]]
80 0.0182488 [[-0.3202447   1.08418322  1.09988284]]
100 0.00528378 [[-0.17232074  1.04529822  1.0537461 ]]
120 0.00152987 [[-0.0927242   1.0243746   1.02892029]]
140 0.000442965 [[-0.04989399  1.01311576  1.0155617 ]]
160 0.000128256 [[-0.02684749  1.00705743  1.00837362]]
180 3.71349e-05 [[-0.0144463   1.00379765  1.00450575]]
200 1.07518e-05 [[-0.00777342  1.00204337  1.00242448]]
220 3.11323e-06 [[-0.00418284  1.00109959  1.00130463]]
240 9.01458e-07 [[-0.00225071  1.00059164  1.00070202]]
260 2.61014e-07 [[-0.00121108  1.00031841  1.00037777]]
280 7.55424e-08 [[ -6.51612820e-04   1.00017142e+00   1.00020325e+00]]
300 2.19073e-08 [[ -3.50635702e-04   1.00009227e+00   1.00010943e+00]]
320 6.33089e-09 [[ -1.88689912e-04   1.00004947e+00   1.00005877e+00]]
340 1.83591e-09 [[ -1.015